### ISSUE TITLE
bluez-alsa as audio sink, print bluealsa: Missing RTP packet:

### ISSUE THREAD

**Issue by wuzhe3377** [Arkq/bluez-alsa#110]
Hi:
    1. bluealsa -i hci0  --profile=a2dp-sink
    2. bluealsa-aplay -i hci0 -d bluetooth --profile-a2dp -vv 00:00:00:00:00:00
    when phone connected to my device to playing music, after a period of time, there are the following  
    logs：     
bluealsa: bluez.c:1034: Signal: PropertiesChanged: org.bluez.MediaTransport1
bluealsa: ctl.c:536: Client closed connection: 11
bluealsa: ctl.c:586: +-+-
bluealsa: io.c:110: FIFO endpoint has been closed: 14
bluealsa: transport.c:973: Closing PCM: 14
bluealsa: ctl.c:536: Client closed connection: 12
bluealsa: transport.c:973: Closing PCM: 14
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:565: New client accepted: 11
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:565: New client accepted: 12
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:318: PCM requested for 4C:7C:5F:99:3F:B6 type 1 stream 1
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:536: Client closed connection: 11
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:536: Client closed connection: 12
bluealsa: transport.c:973: Closing PCM: 15
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:565: New client accepted: 11
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:565: New client accepted: 12
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:318: PCM requested for 4C:7C:5F:99:3F:B6 type 1 stream 1
bluealsa: ctl.c:586: +-+-
bluealsa: bluez.c:609: Endpoint method call: org.bluez.MediaEndpoint1.ClearConfiguration()
bluealsa: transport.c:348: Freeing transport: A2DP Sink (SBC)
bluealsa: transport.c:847: Releasing transport: A2DP Sink (SBC)
bluealsa: transport.c:875: Closing BT: 13
bluealsa: transport.c:999: Exiting IO thread
bluealsa: transport.c:973: Closing PCM: 15
bluealsa: ctl.c:580: Emitting notification: 100 => 11
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:416: PCM close for 4C:7C:5F:99:3F:B6 type 1 stream 1
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:536: Client closed connection: 12
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:586: +-+-
bluealsa: bluez.c:609: Endpoint method call: org.bluez.MediaEndpoint1.SetConfiguration()
bluealsa: bluez.c:541: A2DP Sink (SBC) configured for device 4C:49:E3:32:7E:DB
bluealsa: bluez.c:543: Configuration: channels: 2, sampling: 44100
bluealsa: transport.c:675: State transition: 0 -> 0
bluealsa: ctl.c:580: Emitting notification: 1 => 11
bluealsa: ctl.c:586: +-+-
bluealsa: bluez.c:663: Endpoint already registered: /A2DP/SBC/Sink/2
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:565: New client accepted: 12
bluealsa: ctl.c:586: +-+-
bluealsa: ctl.c:318: PCM requested for 4C:49:E3:32:7E:DB type 1 stream 1
bluealsa: ctl.c:586: +-+-
bluealsa: bluez.c:1034: Signal: PropertiesChanged: org.bluez.MediaTransport1
bluealsa: transport.c:675: State transition: 0 -> 1
bluealsa: transport.c:821: New transport: 13 (MTU: R:900 W:1008)
bluealsa: bluez.c:1034: Signal: PropertiesChanged: org.bluez.MediaTransport1
bluealsa: transport.c:675: State transition: 1 -> 2
bluealsa: io.c:198: Starting IO loop: A2DP Sink (SBC)
bluealsa: transport.c:104: Created new IO thread: A2DP Sink (SBC)

bluealsa: Missing RTP packet: 26888 != 26887
bluealsa: Missing RTP packet: 28630 != 28629
bluealsa: Missing RTP packet: 29927 != 29926
bluealsa: Missing RTP packet: 30099 != 30098
bluealsa: Missing RTP packet: 30848 != 30847
bluealsa: Missing RTP packet: 31146 != 31145
bluealsa: Missing RTP packet: 31388 != 31387
bluealsa: Missing RTP packet: 31890 != 31889
bluealsa: Missing RTP packet: 32235 != 32234
bluealsa: Missing RTP packet: 32319 != 32318
bluealsa: Missing RTP packet: 32361 != 32360
bluealsa: Missing RTP packet: 32703 != 32702
bluealsa: Missing RTP packet: 34117 != 34116
bluealsa: Missing RTP packet: 35761 != 35760
bluealsa: Missing RTP packet: 35864 != 35863
bluealsa: Missing RTP packet: 35929 != 35928
bluealsa: Missing RTP packet: 36009 != 36008
bluealsa: Missing RTP packet: 36529 != 36528
bluealsa: Missing RTP packet: 37100 != 37099
bluealsa: Missing RTP packet: 37399 != 37398
bluealsa: Missing RTP packet: 38793 != 38792
bluealsa: Missing RTP packet: 39092 != 39091
bluealsa: Missing RTP packet: 39338 != 39337
bluealsa: Missing RTP packet: 40305 != 40304
bluealsa: Missing RTP packet: 41107 != 41106
bluealsa: Missing RTP packet: 41550 != 41549
bluealsa: Missing RTP packet: 41630 != 41629
bluealsa: Missing RTP packet: 41802 != 41801
bluealsa: Missing RTP packet: 41854 != 41853
bluealsa: Missing RTP packet: 43784 != 43783
bluealsa: Missing RTP packet: 45281 != 45280
bluealsa: Missing RTP packet: 45406 != 45405
bluealsa: Missing RTP packet: 45509 != 45508
bluealsa: Missing RTP packet: 46274 != 46273
bluealsa: Missing RTP packet: 47614 != 47613
bluealsa: Missing RTP packet: 47642 != 47641
 
  Does anyone know what the printing problem is and how to solve it?

**Comment by Arkq** [comment]
This issue is not related to the bluez-alsa per se, closing.
