### ISSUE TITLE
disable audio profil to pair (stretch)

### ISSUE THREAD

**Issue by JLFra** [Arkq/bluez-alsa#115]
Hello,
I do not want to have the A2dp agent that allows to make bluetooth visible when pairing bluetooth in audio mode (on stretch)
Indeed, if we make visible the bluetooth raspberry, it appears in the list of bluetooth to apairer, but with the icon of a helmet.
On Jessie, we had no problem, we had a classic icon that used the bluetooth to transmit data.
For example we do a sudo rfcomm watch hci0, then we launch a client as bluetooth serial controler, it worked perfectly. Now it's impossible to connect a bluetooth client to the raspberry pi, because the latter is declared as an audio device! (audio headphone icon).
Could you tell me the method to come back as the basic config that was present on Jessie and that worked perfectly.
I have the impression that the bluetooth raspberry can only use an audio client !?
In fact i don't want audio connexions.
Thank you for your very specific answers.
Thank you for your help.
Your sincerely.

Julien

**Comment by Arkq** [comment]
I don't think it is a right place for a Linux distribution related issue.... However, if you want to disable audio profile completely, do not run `bluealsa` service on your machine.

I'm closing this issue as it is not a bluealsa bug.
