### ISSUE TITLE
bluealsa-aplay volume very low

### ISSUE THREAD

**Issue by eburi** [Arkq/bluez-alsa#122]
Hi,

I got bluez-alsa working on a Raspberry Pi, streaming sound from my smartphone to a speaker connected to the audio out of the Pi. 

One thing that is really annoying though, is the volume range of the sound coming in through bluez-alsa. I can only hear something from 70%/75% up to 100%. Under 70% it's all silent.
Volume control from the smartphone is working fine, but not making any difference under 75% (just silent).

```
$ amixer -D bluealsa sset 'Hopp YB - A2DP' 100%
Simple mixer control 'Hopp YB - A2DP',0
  Capabilities: cvolume cswitch
  Capture channels: Front Left - Front Right
  Limits: Capture 0 - 127
  Front Left: Capture 127 [100%] [on]
  Front Right: Capture 127 [100%] [on]
```

Any mp3-File played through mpg123 is louder than the sound from the smartphone at 100%. What setting is wrong here? Where can I tune that? 

Running on raspbian:stretch:
```
$ bluealsa --version
1.2.0
$ bluetoothd --version
5.43
```

**Comment by Arkq** [comment]
I had never experienced any issues with volume level, however my phone does not interacts correctly with bluez and volume control is not working... I will try to reproduce it with some other phone.

When you change volume from phone, is there any change in the volume level on the bluealsa side (capture volume is changed from 100% to some other value)?

I've seen in some bluez-alsa fork, that someone has been tinkering with bluealsa-aplay volume control. Maybe indeed there is something wrong there.
