### ISSUE TITLE
expose device to jack

### ISSUE THREAD

**Issue by rhz** [Arkq/bluez-alsa#147]
I'm trying to use bluealsa to make my bluetooth headphones available in jack. I set it up according to these [instructions](https://wiki.archlinux.org/index.php/Bluetooth_headset#Headset_via_Bluez5.2Fbluez-alsa). So far I've been successful in disabling bluetooth discovery in pulseaudio so that bluealsa can capture the device. I can connect the bluetooth headphones without problem using `bluetoothctl` and play a song using
```
aplay -D bluealsa:HCI=hci0,DEV=XX:XX:XX:XX:XX:XX,PROFILE=a2dp filename.wav
```
Also, `alsamixer -D bluealsa` shows A2DP, SCO, and battery.

Jack is running alongside pulseaudio as explained in the [archwiki](https://wiki.archlinux.org/index.php/PulseAudio/Examples#The_KXStudio_method). I tested that this configuration is running correctly in `pavucontrol` and `cadence` and by playing a video through the laptop speakers using `vlc` with the pulseaudio plugin (pulseaudio is redirecting the sound to jack as set up in `pavucontrol`). So pulseaudio, jack and bluealsa seem to be working fine.

The problem is when I try to expose the alsa device for the bluetooth headphones to jack. When using `alsa_out` from [jack2-dbus](https://www.archlinux.org/packages/community/x86_64/jack2-dbus/) I get the following error even though the jack server is running (as evidenced from `cadence`).
```
$ sudo alsa_out -j mpow059 -d bluealsa:HCI=hci0,DEV=XX:XX:XX:XX:XX:XX,PROFILE=a2dp
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Connection Error (Server address of type unix was missing argument path or abstract)
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
jack server not running?              
*** stack smashing detected ***: <unknown> terminated
Aborted
```
And when using [zita-ajbridge](http://kokkinizita.linuxaudio.org/linuxaudio/zita-ajbridge-doc/quickguide.html) I get
```
sudo zita-a2j -j mpow059 -d bluealsa:HCI=hci0,DEV=XX:XX:XX:XX:XX:XX,PROFILE=a2dp
ALSA lib bluealsa-pcm.c:678:(_snd_pcm_bluealsa_open) Couldn't get BlueALSA transport: No such device or address
Can't open ALSA capture device 'bluealsa:HCI=hci0,DEV=XX:XX:XX:XX:XX:XX,PROFILE=a2dp'.
```
Does anyone know how to properly expose the device to jack?

**Comment by sdfg2** [comment]
You are on -exactly- the same mission as I am right now.  I've gotten as far as you.  I think the problem with `alsa_out` is that you are running it as root, when jack (presumably) is running as the user.  I'm trying to figure out the dbus permissions at the moment to allow a user access to to the bluesalsa dbus interface.  (When I tried using `-j` under user with jack running it segfaulted, which is a bug I've seen kicking around various places.  No idea about that, but without `-j` it seems to want to connect fine, except for the dbus permissions.

I have seen numerous questions, queries, bugs, and associated cries for help regarding jack and bluealsa, perhaps an addition to the troubleshooting with instructions on the process would be beneficial?  Or at the very least, can the owner start merging jack issues into a single issue so we can all benefit from the experience?

**Comment by rhz** [comment]
If I run `alsa_out` as a user I get
```
$ alsa_out -d bluealsa:HCI=hci0,DEV=XX:XX:XX:XX:XX:XX,PROFILE=a2dp
WARNING: buffer size does not match: (requested 2048, got 9600)
WARNING: period size does not match: (requested 1024, got 1066)
Segmentation fault (core dumped)
```
If I run `zita-a2j` I get the same output as before
```
$ zita-a2j -j mpow059 -d bluealsa:HCI=hci0,DEV=XX:XX:XX:XX:XX:XX,PROFILE=a2dp
ALSA lib bluealsa-pcm.c:678:(_snd_pcm_bluealsa_open) Couldn't get BlueALSA transport: No such device or address
Can't open ALSA capture device 'bluealsa:HCI=hci0,DEV=XX:XX:XX:XX:XX:XX,PROFILE=a2dp'.
```

Yeah, a guide would be useful. The guide would be like this:
1. compile and possibly install bluealsa (I used [this](https://aur.archlinux.org/packages/bluez-alsa-git))
1. edit file `/etc/dbus-1/system.d/bluetooth.conf` as indicated in the [archwiki](https://wiki.archlinux.org/index.php/Bluetooth_headset#Headset_via_Bluez5.2Fbluez-alsa)
1. comment out the lines in `/etc/pulse/default.pa` that load the modules that autodetect bluetooth devices
1. reload pulseaudio

       $ pulseaudio --kill
       $ pulseaudio --start

1. run bluealsa as root

       $ sudo bluealsa --device=hci0

1. on another terminal, use `bluetoothctl` to connect your bluetooth headphones (assuming the device has been paired before)

       $ bluetoothctl
       Agent registered
       [bluetooth]# connect XX:XX:XX:XX:XX:XX

1. test that the connection is working using `aplay`

       $ aplay -D bluealsa:HCI=hci0,DEV=XX:XX:XX:XX:XX:XX,PROFILE=a2dp file.wav

1. start jack

       $ jack_control start

1. check in `cadence` that jack is running OK and start the alsa and pulseaudio bridge as decribed [here](https://wiki.archlinux.org/index.php/PulseAudio/Examples#The_KXStudio_method) if they haven't been started automatically

       $ cadence

1. use `alsa_out` or `zita-a2j` to expose the bluealsa device to jack

       $ alsa_out -d bluealsa:HCI=hci0,DEV=XX:XX:XX:XX:XX:XX,PROFILE=a2dp


Last step is the one failing.

**Comment by sdfg2** [comment]
9.5.  add your device to the end of `~/.asoundrc`

```
pcm.bluetooth_raw {
    type plug
    slave.pcm {
        type          bluealsa;
        interface     hci0;
        device        XX:XX:XX:XX:XX:XX;
        profile       "a2dp";
    }
    hint {
        show on;
        description "My bluetooth device";
    }
}

ctl.bluetooth_raw {
    type        bluealsa;
    interface   "hci0"
}
```

NOTE:  This has to be added after the alsa-pulseaudio-jack bridge has started, so it already contains the bridge settings for jack.  cadence will pick up the fact that it's a custom .asoundrc and won't overwrite it later on.

I'm not sure if this is -strictly- required, but it vastly simplifies references to the device without the whole bluealsa line.  It also allows for further alsa fun, such as merging devices and channels and so forth (which is why I usually reference it as `_raw`)

**Comment by sdfg2** [comment]
I think I've cracked it.  The segfault error contains `snd_pcm_lfloat_convert_float_integer (libasound.so.2)`, which made me start thinking about the flags.  I added `-p 10000` (period size), and now it starts, the patch shows up in Catia.  Only trouble is I get no sound, but at least it's progress!

All the dbus errors I was getting were bogus to this problem, I think bluez was falling over.  I was consistently getting segfaults like you after a reboot earlier today.

**Comment by rhz** [comment]
Great!

Which bridge isn't working for you?

**Comment by sdfg2** [comment]
No idea, but it fixed itself, somehow.  Now I've just got to troubleshoot netjack2, figure out why the master and slave can't see each other.  But that's not for here :-)  Did you get everything working?

**Comment by ohel** [comment]
This is probably not helpful to you guys unfortunately, but for others who might stumble upon here, I was using JACK1 (0.125) without the dbus interface. I ran it as usual:
```
/usr/bin/jackd -r -p128 -dalsa -dbluetooth -r44100 -p512 -n2 -s -S -P -o2
```
where bluetooth is an ALSA plug device with a bluealsa slave device. It worked without a hitch.

**Comment by perkinslr** [comment]
I got it working via alsa_out by setting the buffer size and periods very small (like 16 for buffer size and 4 for periods).  The audio quality was pretty terrible doing it that way, lots of xruns, but it didn't crash.  

For stable output, you can use `ffmpeg` or anything similar that can output a raw signed 16bit le, 2 channel, bitstream and pipe it to `aplay -f cd -D bluealsa` and get reasonable quality audio.  

I'm thinking I might take a crack at writing a raw wav driver that would cut ALSA/aplay out of the picture and see if that helps performance or quality.

**Comment by crocket** [comment]
@ohel

> /usr/bin/jackd -r -p128 -dalsa -dbluetooth -r44100 -p512 -n2 -s -S -P -o2

Why would you pass `-r` to jackd? `-P 90` is better.

**Comment by crocket** [comment]
@perkinslr 
16 for buffer size and 4 for periods are too small.
Try something like `-p 512 -n 3` or `-p 1024 -n 2` or `-p 1024 -n 3`

**Comment by ohel** [comment]
> @ohel
> 
> > /usr/bin/jackd -r -p128 -dalsa -dbluetooth -r44100 -p512 -n2 -s -S -P -o2
> 
> * Why would you pass `-r` to jackd? `-P 90` is better.
> * `-p128` is unnecessary.
> * `-r 48000` can be better than `-r 44100`.

For the -r: if I'm not using a realtime kernel (which I normally don't), is there any point in using realtime scheduling? Although, I guess it doesn't matter then.
Yeah, 128 seems to be the default number of frames per period.

What do you mean by 48 kHz sampling rate can be better than 44.1 kHz? Doesn't the bluetooth standard work with 44.1 kHz despite bluealsa's --a2dp-force-audio-cd parameter? I'm trying to minimize resampling.

**Comment by crocket** [comment]
`-p 128` before `-d alsa` is

```
-p, --port-max  n
         Set the maximum number of ports the JACK server can manage.  The default value is 256.
```

You also specified `-p 512` after `-d alsa`.

> is there any point in using realtime scheduling?

It is the most important part when your softwares and hardwares are keeping the CPU cores busy.
If you get this wrong, you get xruns and stutters which ruin your audio experience.
Without real-time kernel, you can still combine `CONFIG_RT_GROUP_SCHED` with `cgrulesengd` to allocate 95% of real-time CPU bandwidth to certain processes.

`CONFIG_RT_GROUP_SCHED` AND `cgrulesengd` were good enough until I put a lot of stress on hard disks and CPU cores simultaneously.

**Comment by ohel** [comment]
> `-p 128` before `-d alsa` is
> -p, --port-max  n
>          Set the maximum number of ports the JACK server can manage.  The default value is 256.

So it seems, my first hit from the man page was a bit misleading :) Don't quite remember the options from the heart. I might have copy pasted it from QjackCtl command line originally, doesn't really matter whether it's 128 or 256.

> Without real-time kernel, you can still combine `CONFIG_PREEMPT` and `CONFIG_RT_GROUP_SCHED` with `cgrulesengd` to allocate 95% of real-time CPU bandwidth to certain processes.

Interesting. Might check it out. I think I seemed to get more xruns without the -r option if not using a RT kernel, but this was years ago. I do have a RT kernel also, with which I am able to get crazy low latencies without xruns and pops using JACK. However, with the parameters I use, I don't have much of those problems with a non-RT kernel anyway, at least when not using bluealsa. I haven't tried bluealsa with the RT scheduling, didn't even think it might be the culprit. It's been some time since I last used bluealsa anyway, things have generally probably improved since then.

**Comment by crocket** [comment]
You cannot get low latency audio with bluetooth, yet.
AptX Low Latency is obsolete.
AptX Adaptive promises latencies between 50ms and 80ms.

**Comment by ohel** [comment]
Yeah the latencies seem to be quite terrible with bluetooth. That's where the -p option after -d alsa comes into play, the default period is 1024 but with 512 it mostly works. Listening to music using LDAC the latencies don't matter that much, though.

**Comment by crocket** [comment]
> What do you mean by 48 kHz sampling rate can be better than 44.1 kHz? Doesn't the bluetooth standard work with 44.1 kHz despite bluealsa's --a2dp-force-audio-cd parameter? I'm trying to minimize resampling.

SBC supports sampling rates of up to 48000.
48000Hz makes it easy to make period latency or buffer latency an integer multiple of 1ms although only USB soundcards prefer multiples of 1ms for period latency or buffer latency.

**Comment by crocket** [comment]
I think you should create a pcm device in ~/.asoundrc

**Comment by borine** [comment]
With bluez-alsa release 3.1.0, and recent JACK releases, JACK and BlueALSA are working quite well together. There is now a wiki page with some simple example usage.

**Comment by sdfg2** [comment]
My setup has changed now so any information I have is very outdated, but just thought I'd mention maybe pipewire might be able to do something clever with all this?

**Comment by crocket** [comment]
At this point, I think bluetooth audio is a deadend. I'd stick to wired audio.

**Comment by domichel** [comment]
> With bluez-alsa release 3.1.0, and recent JACK releases, JACK and BlueALSA are working quite well together. There is now a wiki page with some simple example usage: https://github.com/Arkq/bluez-alsa/wiki/Using-BlueALSA-with-the-JACK-Audio-Connection-Kit

Thank You. If someone want a volume control, it work fine together with a custom .asoundrc file as explained here: https://github.com/arkq/bluez-alsa/issues/147#issuecomment-426973620

**Comment by domichel** [comment]
> At this point, I think bluetooth audio is a deadend. I'd stick to wired audio.

It depend on what you want to do. To stream audio at the beach or a private party, bluetooth is cheap and fine. But to do serious work on stage or even into a studio, only wired audio or professional HF radio devices are reliable.
