### ISSUE TITLE
Speech Recording Failed when RPi acts as HFP source 

### ISSUE THREAD

**Issue by lordet01** [Arkq/bluez-alsa#170]
Hi. First, thank you for sharing your great work! I couldn't make my own Bluetooth speaker with Raspberry Pi unless you published this handful project.

Currently, I am making Bluetooth speaker having 2 MEMS microphones for distant phone call with it.
my RPi-based prototype successfully paired with my iPhone7 as hands-free device which supports both HFP and A2DP like other commercial Bluetooth speakers. However, recording using arecord from the device through the phone is failed, while aplay works perfectly. Is the recording functionality is not yet implemented in BlueALSA? or I am missing something? Some advice would tremendously be helpful. Best Regards!

**Comment by Arkq** [comment]
HFP is not working correctly. This issue might be related to #161. In the near future there might be a lot of changes in the HFP area, so stay tuned and be patient :)

**Comment by lryindra** [comment]
set the following command to record from Raspberry Pi's bluetooth:
/usr/bin/hcitool cmd 0x3F 0x01C 0x01 0x02 0x00 0x01 0x01

**Comment by lordet01** [comment]
Now I solved my issue with hfp-ofono protocol which has committed recently. Thanks again for your dedication on this project.
