### ISSUE TITLE
How to configure HSP "wideband speech" mSBC codec with Pulseaudio

### ISSUE THREAD

**Issue by brauliobo** [Arkq/bluez-alsa#187]
How do I achieve better HSP quality using bluez-alsa?

Also, how to use it through pulseaudio?

From https://github.com/EHfive/pulseaudio-modules-bt/issues/32

**Comment by Arkq** [comment]
There is (right now rather outdated) msbc branch in the bluez-alsa repository, which tries to add mSBC support. However, it seems, that it does not work. I was able to positively test mSBC microphone support. Playing PCM data does not work.... and I'm not able to figure out why :/
