### ISSUE TITLE
MPD hardware mixer problem

### ISSUE THREAD

**Issue by skidoo23** [Arkq/bluez-alsa#19]
audio_output {
        type "alsa"
        name "Bluetooth Speaker"
        device "bluealsa:HCI=hci0,DEV=11:22:33:44:55:66,PROFILE=a2dp"
        mixer_type "software"
}

Working config.

# amixer -D bluealsa:HCI=hci0 sset 'MS425 - A2DP' 100% # loud
# amixer -D bluealsa:HCI=hci0 sset 'MS425 - A2DP' 5% # quiet

Looks like there is a hardware mixer.

audio_output {
        type "alsa"
        name "Bluetooth Speaker"
        device "bluealsa:HCI=hci0,DEV=11:22:33:44:55:66,PROFILE=a2dp"
        mixer_type "hardware"
        mixer_device "bluealsa:HCI=hci0"
        mixer_control "MS425 - A2DP"
}

Results in mpd.log

mpd: control.c:223: snd_ctl_poll_descriptors: Assertion `ctl && pfds' failed.
Dec 21 23:44 : zeroconf: No global port, disabling zeroconf
(...)

Debian Strech x64, MPD git, BlueZ 5.43, ALSA 1.1.2, BlueALSA git

Reported to MPD bugtracker. Reply was "An assertion failure is always a bug in the code which raises the failure. This "control.c" file is not part of MPD, thus this is not a MPD bug." Any help?

**Comment by Arkq** [comment]
@skidoo23, please check if code from [event](https://github.com/Arkq/bluez-alsa/tree/events) branch works for you. I'm not MPD user, so it is hard for me to tell if everything is OK. By "everything OK" I mean, that there is no segfault. Using hardware mixer might not work as expected, though. Event notifications are not implemented yet, so MPD might not be able to discover new controls (connected Bluetooth devices, e.g. headset) if Bluetooth device was connected after MPD has been started.

PS.
BlueALSA hardware mixer is in fact a software mixer. If you want to use "true" hardware volume control, you have to add `--a2dp-volume` option (to bluealsa server). However, it might not work (it is not working for me without patching bluez code). See [this](https://github.com/Arkq/bluez-alsa/commit/d567b847b068d11f3d1c1179a6baefa094035850) commit message for more details.
