### ISSUE TITLE
32 bit rather then 16 bit

### ISSUE THREAD

**Issue by flatmax** [Arkq/bluez-alsa#198]
Is it possible to use 32 bit audio word sizes rather then 16 bit audio word sizes ?

**Comment by Arkq** [comment]
No, currently only 16-bit PCM is supported. Supporting 24 or 32-bit PCM
will require some refactoring.

>

**Comment by flatmax** [comment]
can you please point to the locations where this will require refactoring ?

**Comment by Arkq** [comment]
For extended bit support, please look at @joerg-krause's work: https://github.com/joerg-krause/bluez-alsa/commits/volume-aptx-sink-2.0.0
