### ISSUE TITLE
fdk-aac compile problem

### ISSUE THREAD

**Issue by erikly01** [Arkq/bluez-alsa#20]
Starting with **fdk-aac 0.1.4**, AOT_MP2_AAC_LC was removed.  This is preventing io.c line 789 from compiling.  From what I can tell it simply maps to AOT_AAC_LC anyway.

Possible fix: line 788 of io.c

	case AAC_OBJECT_TYPE_MPEG2_AAC_LC:
	case AAC_OBJECT_TYPE_MPEG4_AAC_LC:
		aot = AOT_AAC_LC;
		break;

**Comment by Arkq** [comment]
@erikly01, thanks for reporting this and sorry for such a late reply. I was very busy lately.

I hope, that this change will not break anything - I'm not able to test it properly. Bluetooth specification requires MPEG2 AAC audio object type to be present - it is the only mandatory object type...
