### ISSUE TITLE
No audio with a2dp-sink profile

### ISSUE THREAD

**Issue by leoc123** [Arkq/bluez-alsa#209]
Hi, I am awfully knew to this and I still dont know if I set this up correctly and there's no direct guide/tutorial on this. Using a raspberry pi zero w.

Essentially all I have done is a clean install of stretch and ran bluealsa -p a2dp-sink

Nothing happens and now my iPhone can discover the pi.

I pair and connect successfully now as I play music on my iPhone where is the audio coming from the pi? I converted my audio out to come from the pins but nothing is happening. I am confused as what I am suppose to expect from using the pi as a sink. Is there suppose to be anything indication of anything after you type in bluealsa -p a2dp-sink? 

Note of issues: Why is that I need to remove the contents of bluealsa inorder to run bluealsa -p a2dp-sink? I always get bluealsa: Couldn't initialize controller thread: Bad file descriptor, unless I remove the contents of the folder in var/run/bluealsa.

**Comment by Arkq** [comment]
> I pair and connect successfully now as I play music on my iPhone where is the audio coming from the pi?

Is should be available on virtual PCM device created for connected iPhone. Check `amixer -D bluealsa`.

> Bad file descriptor, unless I remove the contents of the folder in var/run/bluealsa.

This part of bluealsa has been rewritten. Right now there is no controller thread based on /var/run/bluealsa socket.

Closing issue as it is for < 2.0.0 version of bluez-alsa.
