### ISSUE TITLE
Couldn't acquire D-Bus name: org.bluealsa if more than one instance runs

### ISSUE THREAD

**Issue by tmp6154** [Arkq/bluez-alsa#217]
When running multiple instances (e.g. for multiple speakers) - following error appears in the log:

Couldn't acquire D-Bus name: org.bluealsa

Maybe, it's possible to add, e.g. index (org.bluealsa1) if primary name is occupied, instead of failing bluealsa outright?

**Comment by Arkq** [comment]
It is possible like this: `bluealsa --dbus=suffix`. Please note, that this option requires D-Bus policy file to be modified in order to allow sending messages to the new service - by default only "org.bluealsa" is allowed.
