### ISSUE TITLE
Can't record sound run bluealsa with hfp-ofono profile

### ISSUE THREAD

**Issue by xuewenxu** [Arkq/bluez-alsa#226]
I was run bluealsa like this: sudo bluealsa -p a2dp-source -p a2dp-sink -p hfp-ofono,  the log as follow:
bluealsa: ../../src/main.c:283: Disabling native HFP due to enabled oFono
bluealsa: ../../src/main.c:297: dbus address:unix:path=/var/run/dbus/system_bus_socket
bluealsa: ../../src/bluez.c:1166: object_path:/org/bluez
bluealsa: ../../src/bluez.c:1168: interface0:org.freedesktop.DBus.Introspectable
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.AgentManager1
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.ProfileManager1
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.Alert1
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.HealthManager1
bluealsa: ../../src/bluez.c:1166: object_path:/org/bluez/hci0
bluealsa: ../../src/bluez.c:1168: interface0:org.freedesktop.DBus.Introspectable
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.Adapter1
bluealsa: ../../src/bluez.c:1171: object path:/org/bluez/hci0, interface:org.bluez.Adapter1, property:Address
bluealsa: ../../src/bluez.c:63: adapter path:/org/bluez/hci0, adapter_address:B8:27:EB:29:37:81
bluealsa: ../../src/bluez.c:1171: object path:/org/bluez/hci0, interface:org.bluez.Adapter1, property:Name
bluealsa: ../../src/bluez.c:1171: object path:/org/bluez/hci0, interface:org.bluez.Adapter1, property:Alias
bluealsa: ../../src/bluez.c:1171: object path:/org/bluez/hci0, interface:org.bluez.Adapter1, property:Class
bluealsa: ../../src/bluez.c:1171: object path:/org/bluez/hci0, interface:org.bluez.Adapter1, property:Powered
bluealsa: ../../src/bluez.c:1171: object path:/org/bluez/hci0, interface:org.bluez.Adapter1, property:Discoverable
bluealsa: ../../src/bluez.c:1171: object path:/org/bluez/hci0, interface:org.bluez.Adapter1, property:DiscoverableTimeout
bluealsa: ../../src/bluez.c:1171: object path:/org/bluez/hci0, interface:org.bluez.Adapter1, property:Pairable
bluealsa: ../../src/bluez.c:1171: object path:/org/bluez/hci0, interface:org.bluez.Adapter1, property:PairableTimeout
bluealsa: ../../src/bluez.c:1171: object path:/org/bluez/hci0, interface:org.bluez.Adapter1, property:Discovering
bluealsa: ../../src/bluez.c:1171: object path:/org/bluez/hci0, interface:org.bluez.Adapter1, property:UUIDs
bluealsa: ../../src/bluez.c:1171: object path:/org/bluez/hci0, interface:org.bluez.Adapter1, property:Modalias
bluealsa: ../../src/bluez.c:1168: interface0:org.freedesktop.DBus.Properties
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.Media1
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.CyclingSpeedManager1
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.HeartRateManager1
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.ThermometerManager1
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.NetworkServer1
bluealsa: ../../src/bluez.c:1166: object_path:/org/bluez/hci0/dev_1C_52_16_17_A8_F4
bluealsa: ../../src/bluez.c:1168: interface0:org.freedesktop.DBus.Introspectable
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.Device1
bluealsa: ../../src/bluez.c:1168: interface0:org.freedesktop.DBus.Properties
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.MediaControl1
bluealsa: ../../src/bluez.c:1166: object_path:/org/bluez/hci0/dev_DC_F0_90_09_4B_B6
bluealsa: ../../src/bluez.c:1168: interface0:org.freedesktop.DBus.Introspectable
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.Device1
bluealsa: ../../src/bluez.c:1168: interface0:org.freedesktop.DBus.Properties
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.ProximityReporter1
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.Network1
bluealsa: ../../src/bluez.c:1168: interface0:org.bluez.MediaControl1
bluealsa: ../../src/ba-adapter.c:61: ba_dbus_path:/org/bluealsa/hci0, bluez_dbus_path:/org/bluez/hci0
bluealsa: ../../src/ctl.c:666: saddr.sun_path:/var/run/bluealsa/hci0
bluealsa: ../../src/ctl.c:513: Starting controller loop: hci0
bluealsa: ../../src/bluez.c:802: Registering endpoint: /org/bluez/hci0/A2DP/MPEG24/Source/1
bluealsa: ../../src/bluez.c:802: Registering endpoint: /org/bluez/hci0/A2DP/MPEG24/Sink/1
bluealsa: ../../src/bluez.c:802: Registering endpoint: /org/bluez/hci0/A2DP/SBC/Source/1
bluealsa: ../../src/bluez.c:802: Registering endpoint: /org/bluez/hci0/A2DP/SBC/Sink/1
bluealsa: ../../src/ofono.c:474: Registering oFono audio agent: /org/bluez/HFP/oFono
bluealsa: ../../src/ofono.c:264: ofono_get_all_cards be called!
bluealsa: ../../src/ofono.c:291: send_path:(null)
bluealsa: ../../src/ofono.c:292: sender::1.3
bluealsa: ../../src/main.c:332: Acquiring D-Bus service name: org.bluealsa
bluealsa: ../../src/main.c:337: Starting main dispatching loop

 Run arecord capture.wav command  I was get errors:
../../../src/asound/../shared/ctl-client.c:108: Connecting to socket: /var/run/bluealsa/hci0
../../../src/asound/../shared/ctl-client.c:238: Getting transport for 1C:52:16:17:A8:F4 type 0x82
../../../src/asound/../shared/ctl-client.c:253: len:1, transport:18
ALSA lib ../../../src/asound/bluealsa-pcm.c:714:(_snd_pcm_bluealsa_open) Couldn't get BlueALSA transport: No such device or address
arecord: main:722: audio open error: No such device or address

From the bluealsa's logs when it started up  I founded that the function "ofono_card_add" seems not be called.
Hardware is  Raspberry Pi 3 Model B.
~/.asoundrc file as follow:
 pcm.!default {
     type asym
     capture.pcm "btmic"
    playback.pcm "btspeaker"
 }
 
pcm.btspeaker {
     type plug
     slave.pcm {
         type bluealsa
        device "1C:52:16:17:A8:F4"
         profile "a2dp"
     }
}
 
 pcm.btmic {
     type plug
    slave.pcm {
       type bluealsa
         device "1C:52:16:17:A8:F4"
         profile "sco"
    }
 }

**Comment by Arkq** [comment]
Please try new master code, since a LOT of changes has been made to HSP/HFP profiles.
