### ISSUE TITLE
befriend alsa bluetooth with ladspa module/device

### ISSUE THREAD

**Issue by Sergey82** [Arkq/bluez-alsa#227]
do anyone know how to make one ladspa module/device work with this alsa BT
as i posted before the alsa BT works fine, but previously i had audio normalizer with ladspa. now the sounds when something blasting, blasting my ears as well. is it possible?

**Comment by borine** [comment]
This question has had no response for some time now. I am closing it, but please feel free to re-open if your ladspa module still has problems with the latest bluealsa code.
