### ISSUE TITLE
Can't access the unix fd from unprivileged lxc container

### ISSUE THREAD

**Issue by subjectxbj** [Arkq/bluez-alsa#229]
Hi @Arkq,

Right now on my system. Bluez is running in the host, and bluealsa is running withing a privileged lxc container. and I mount the DBUS socket to the lxc container. Everything works good.  

But when I change the container to a unprivileged container, it seems bluealsa can't work properly. For the unprivileged container, I have setup uidmap, to map the uid 0 in the container to uid 10000 in the host.

When bluealsa try to acquire the transport, it report error in function transport_acquire_bt_a2dp() at the line:

```
t->bt_fd = g_unix_fd_list_get(fd_list, 0, &err);
```

The error log is :
```
g_unix_fd_list_get: assertion 'g_is_unix_fd_list (list)' failed
```

Generally when unprivileged container want to access a unix socket in the host, we need to bind this unix socket to a file, and explicitly mount the file in the container as well, then container can open this file to access the socket. That is how we did with the dbus socket.

But with the A2DP transport unix socket, it is not bind to any file, so unprivileged container can't access that socket. Not sure if there is any way to resolve this problem.

**Comment by Arkq** [comment]
Bluealsa utilizes file descriptor passing via Unix socket in two places -
acquiring A2DP transport (mechanism exposed by bluez D-Bus API) and
providing PCM pipe and control socket to clients. This way of transferring
FDs is rather tightly bound to bluez-alsa architecture (it simplifies
open/close synchronization), so if there is no way of transferring FD via
Unix socket to unprivileged container, I'm afraid there is no much we can
do :/
