### ISSUE TITLE
no sound in vlc when trying to play youtube url

### ISSUE THREAD

**Issue by phaoost** [Arkq/bluez-alsa#230]
Hello,

I am getting no sound on bluealsa when using vlc to play youtube url

**Comment by Arkq** [comment]
VLC had some issues with bluez-alsa ALSA PCM plug-in delay reporting. It has been greatly improved in the `bluez-alsa-3.0.0`. Please, test with the newest code and reopen this issue if the problem still occurs (also please add `vlc` and `alsa-lib` versions).
