### ISSUE TITLE
snd_mixer_attach: Can't attach mixer: -2:No such file or directory

### ISSUE THREAD

**Issue by antonbutanaev** [Arkq/bluez-alsa#236]
Hi!

I successfully play music using device bluealsa:HCI=hci0,C0:7A:A5:01:48:F0,PROFILE=a2dp. But when I call snd_mixer_attach with this string, I got -2:No such file or directory error. Here is my /etc/asound.conf:

```
pcm.mono {
    type route
        slave {
            pcm default
            channels 2
        }
    ttable.0.0 1
    ttable.0.1 1
}
```

**Comment by borine** [comment]
rather late with this reply, but for the record:

snd_mixer_attach() requires the name of a ctl device, not a pcm device. For bluealsa the ctl is simply called "bluealsa"
