### ISSUE TITLE
Is it possible to record from and play on a bluetooth device?

### ISSUE THREAD

**Issue by crocket** [Arkq/bluez-alsa#244]
I want to record from a bluetooth device(e.g., smartphone) and play on another bluetooth device(e.g., bluetooth speaker) simultaneously.

Is that possible?

iPad or iPhone --(record)--> bluez-alsa --(play)--> wired speakers or bluetooth speaker
Local ALSA application --> bluez-alsa --(play)--> bluetooth speaker

**Comment by Arkq** [comment]
Yes, it should be possible (if you're talking about A2DP). Just connect both devices and use e.g. `bluealsa-aplay` to play audio from iPhone. However, it is not possible right now to stream more than one stream into bluetooth speaker (there is no mixer), incoming audio has to be played on wired speaker.

**Comment by crocket** [comment]
Is it possible to use ALSA dmix to combine two streams into one and send it to bluetooth speaker?

**Comment by Arkq** [comment]
No, unfortunately it is not possible. These plug-ins require hardware sound dard with timer which is used for synchronization. See #48.

**Comment by crocket** [comment]
What if ALSA dmix outputs to SPDIF output which is connected to SPDIF input which then is read from bluealsa?

**Comment by Arkq** [comment]
The problem right now is that bluealsa can handle only one PCM stream (input and output) and the usage of dmix is not possible. So everything, which allows to externally mix  PCM streams and forward them to bluealsa might do the trick. You have to try it and see the results, though.

**Comment by crocket** [comment]
I already use SPDIF trick to route ALSA dmix to JACK although I am going to remove JACK and use ALSA only. I guess it can also work for bluealsa as long as bluealsa can read from SPDIF input.

**Comment by Arkq** [comment]
> I guess it can also work for bluealsa as long as bluealsa can read from SPDIF input.

If it's standard ALSA interface (PCM), then you can use arecord|aplay, otherwise you will have to create some forwarding (or modify bluealsa to support reading from SPDIF). You might use bluealsa D-Bus API (omit ALSA library which might add additional overhead and delay). See bluealsa-aplay for reference implementation.

**Comment by crocket** [comment]
You can also use ALSA loopback device, but when I used ALSA loopback, it caused a lot of pops.

https://alsa.opensrc.org/Jack_and_Loopback_device_as_Alsa-to-Jack_bridge
