### ISSUE TITLE
i can't set bluealsa to default

### ISSUE THREAD

**Issue by zxc503** [Arkq/bluez-alsa#251]
my .asoundrc is
```
pcm.bluealsa { 
  type plug 
  slave.pcm { 
      type bluealsa 
      device "CC:4B:73:3F:9E:49" 
      profile "a2dp" 
    }
}
pcm.!default {
    type plug 
    slave.pcm { 
      type bluealsa 
      device "CC:4B:73:3F:9E:49" 
      profile "a2dp" 
    }
}
```
i can use command `aplay -D bluealsa sound.wav` to play sound.wav
but i can't use `aplay -D default sound.wav` to play sound.wav
It shows that Playing WAVE 'sound.wav' : Signed 16 bit Little Endian, Rate 8000 Hz, Stereo ,but  it didn't play the sound

**Comment by ab1jx** [comment]
This doesn't actually set it to the default device, you still have to specify the bluealsa device.  I'd like to get it working with Audacity, which has its own device scheme.  If there was a way to make bluealsa the default when you want then change it back when you want that would be the most transparent solution.
