### ISSUE TITLE
how to connect to multiple speakers using rpi built in module?

### ISSUE THREAD

**Issue by sherifomran** [Arkq/bluez-alsa#255]
I can connect to one speaker and play audio using mpg123 -a dev ID and it works fine as long as i keep the connection alive. 
But when i need to play on another speaker, i have to connect to the other speaker (bluetoothctl connect speakerID) and press on the on button on this speaker to connect, and this will disconnect the first speaker connection  ?
Is there another way to connect once to speakers and keep their connection alive in order not to get into sleep mode?

thanks

**Comment by borine** [comment]
This issue has had no updates for over 18 months so I am closing it as there have been many changes to the bluez-alsa code since it was raised. If this problem still exists with the latest bluez-alsa code, please feel free to re-open.
