### ISSUE TITLE
How to integrate bluetooth connection in c++ application

### ISSUE THREAD

**Issue by daniele86rm** [Arkq/bluez-alsa#263]
I'm integrating a bluetooth connection in a qt (c++) application. I'm using example "4.3" described on https://people.csail.mit.edu/albert/bluez-intro/ guide to connect a bluetooth device.
Connection is working fine but when I run "alsamixer -D bluealsa" command, sco and a2dp profile are not connected. 
Instead when I connect bluetooth device from "bluetoothctl", sco and a2dp profile are connected.
In my source code, after calling

// connect to server
status = connect(s, (struct sockaddr *)&addr, sizeof(addr));

should I call something in my source code?

There is an example on how to integrate bluetooth connection via source code?
Thanks in advance.

Best Regards
Daniele

**Comment by killerkalamari** [comment]
I believe bluetoothctl uses dbus to initiate the connection. In my application I did not want to link against any dbus libraries, so I am shelling out to call bluetoothctl. I run it like "echo connect XX:XX:XX:XX:XX | bluetoothctl" to avoid having to automate the bluetoothctl REPL, although you could probably use the "expect" tool as well.

**Comment by daniele86rm** [comment]
Hi Killerkalamari,
I'm trying to run "echo connect XX:XX:XX:XX:XX | bluetoothctl" in my application but how do You know if bluetooth is connected/disconnected? How do you parse output of executed command to know status of bluetooth device? Furthermore when I run commands I obtain the following error:
(bluetoothctl:6586): GLib-CRITICAL **: Source ID 55 was not found when attempting to remove it
but I belive this error is negligible because the bluetooth device seems to be connected correctly.

**Comment by borine** [comment]
- Re `GLib-CRITICAL **: Source ID 55`:  I think this is from a older version of bluetoothctl that required the "quit" command before closing. If I'm right then using:
```echo -e "connect XX:XX:XX:XX:XX:XX\nquit"  | bluetoothctl```
 should get rid of the error message.
- Re parsing bluetoothctl output: scripting with bluetoothctl is hard. The connect command gives no useful output, and does not even wait for the connection to complete. You could try
```echo -e "info XX:XX:XX:XX:XX:XX\nquit" | bluetoothctl | grep Connected```
but you cannot tell whether the last connect request failed or has just not completed yet.

**Comment by killerkalamari** [comment]
The programs bt-device and dbus-monitor can provide connection status, but as borine said, you can't instantly tell if the connect failed. If I were doing it again, I'd probably just use the dbus library.

**Comment by daniele86rm** [comment]
Many thanks, the following code to connect A2DP and SCO profile is working fine:

```
FILE *fp,*outputfile;
char var[40];

fp = popen("echo -e connect 00:1F:82:3A:6E:5F\nquit | bluetoothctl +%s", "r");
while(fgets(var, sizeof(var), fp) != NULL) {
     printf("%s", var);
}
pclose(fp);

outputfile = fopen("text.txt", "a");
fprintf(outputfile,"%s\n",var);
fclose(outputfile);
```
and also 
echo -e "info XX:XX:XX:XX:XX:XX\nquit" | bluetoothctl | grep Connected
command to know bluetooth device status.
But now I don't know how to connect a RFCOMM socket (for example QBluetoothSocket) to read also bluetooth messages. After connecting A2DP and SCO profile, when I connect socket on RFCOMM port with connectToService function of QBluetoothSocket, automatically A2DP and SCO profile are disconnected. I have to find a solution because I should parse some bluetooth messages.

**Comment by daniele86rm** [comment]
I have noted that blualsa log the following messages afeter I have connected my bluetooth Walketalkie:

/usr/bin/bluealsa: Unsupported AT message: CMD: command:+CTXD, value:(null)
/usr/bin/bluealsa: Unsupported AT message: SET: command:^PTT, value:1
/usr/bin/bluealsa: Unsupported AT message: SET: command:+CTKST, value:0,1
/usr/bin/bluealsa: Unsupported AT message: SET: command:+PTT, value:101,1
/usr/bin/bluealsa: Invalid AT message: ET=100;VI=2;SI=1;TI=1;AT=3;MN=ACCESSORY-VER-1.0.0;FC=13;FAT^PTT=0T=TALK,0;TI=1;

I should to parse some of this messages, how can I capture them in my c ++ application?

**Comment by Arkq** [comment]
Via dbus, see utils/rfcomm.c which is a reference implementation of rfcomm external handling.

**Comment by daniele86rm** [comment]
Many thanks, I have used dbus library as in rfcomm.c and now I'm able to read AT messages.
