### ISSUE TITLE
add SBC XQ mode (patch included)

### ISSUE THREAD

**Issue by csch10** [Arkq/bluez-alsa#272]
I recently came across http://soundexpert.org/articles/-/blogs/audio-quality-of-sbc-xq-bluetooth-audio-codec and realized that only very minor changes would be necessary to bluez-alsa to support these _SBC XQ_ settings. The simple changes in the attached patch work for me since bluez-alsa chooses the other settings by default, if available.

[0001-added-simple-SBC-XQ-from-soundexpert-org-blog.txt](https://github.com/Arkq/bluez-alsa/files/3908343/0001-added-simple-SBC-XQ-from-soundexpert-org-blog.txt)

**Comment by Arkq** [comment]
Thanks, patch applied with small changes/cleanup - when dual channel mode is not available in the remote device, the available one will be used instead of hard failing.
