### ISSUE TITLE
Remote bluetooth device stauts, connected or disconnected

### ISSUE THREAD

**Issue by daniele86rm** [Arkq/bluez-alsa#275]
How can I get information about remote bluetooth status (connected/disconnected)? Is possible to get information from dbus or is not the correct way? What function or file I can see in this project to know bluetooth status? At the moment, from my application I'm running 
`echo -e "info bluetooth_address\nquit\ | bluetoothctl | grep Connected`
and I'm parsing connected status (yes or not), but if I run this command every 1 second to know the bluetooth status I see that there are small lags on my application, sure is not the correct way to read bluetooth status (connection and disconnection events). I'm thinking to get informations from dbus, as described in refcomm project file. Trying to open rfcomm I know if bluetooth device is connected or not, is the correct way to implement this feature? Thanks in advance.

Best Regards
Daniele

**Comment by juliandc1969** [comment]
Hi,
Most of the information you need is available via DBus. Do something like:
dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_A4_E9_75_CD_87_85/fd0 org.freedesktop.DBus.Properties.GetAll string:"org.bluez.MediaTransport1"
This will display the transport state of your current connection. 

Change the address to suit your device => A4_E9_75_CD_87_85/fd0   You can probably get this address from DFeet ( Linux/Ubuntu ).

There's some Python code sites around that connect to DBus to "remote control" your device you're connected to like https://scribles.net/controlling-bluetooth-audio-on-raspberry-pi/ for example.
Via DBus you can control play/pause/volume etc. Be aware that not all devices ( iPads, Android ) and their associated apps will supply the full suite of AVRCP - i.e iPad Youtube won't give play/pause if you keep the application maximised; the transport will time-put after 1 minute if paused or if Youtube is minimised..  

If you compile your bluealsa then in bluez.c you can dump out all sorts of DBus status and current music info with a little hacking. You can add another PropertiesChanged for BLUEZ_IFACE_MEDIA_PLAYER_1 and/or BLUEZ_IFACE_MEDIA_TRANSPORT. Also try starting bluealsa in debug mode.
