### ISSUE TITLE
Unknown PCM

### ISSUE THREAD

**Issue by tomg-66** [Arkq/bluez-alsa#299]
aplay can't open the pcm.  When installing and running bluealsa, I try to run aplay with the following command:

 aplay -D bluealsa:HCI=hci0,DEV=00:25:02:09:0C:A3,PROFILE=a2dp Audio.raw

The result is 

ALSA lib ../../../alsa-lib-1.1.8/src/pcm/pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa:HCI=hci0,DEV=00:25:02:09:0C:A3,PROFILE=a2dp
aplay: main:828: audio open error: No such file or directory

How do i register this pcm with alsa?

This is alsa 1.1.8, bluez-alsa 1.3.0

**Comment by tomg-66** [comment]
well, to follow up to my own post....

The issue was that /usr/share/alsa.conf didn't search either /etc/alsa/conf.d or /usr/share/alsa/alsa.conf.d.  modifying that made it so that it will find the PCM.  Now when I play something it seems to think it's working, but I can't hear anything.

tom

**Comment by borine** [comment]
Original issue was resolved by issue author. As for lack of sound, without any debug info there's little that anyone can do to help. After a year, I'm guessing this issue can be closed.
