### ISSUE TITLE
Beginning of wav file is not playing (Raspberry pi)

### ISSUE THREAD

**Issue by imsunburnt** [Arkq/bluez-alsa#318]
When I play a wav file the beginning 1 second of the file is not playing.  This happens when using aplay.  I am running on buster-lite 2019-09-26.  This also happens when using mplayer to play mp3 files.  I was wondering if there were some settings that might help with this, in bluealsa, .asoundrc etc.

Commands:
aplay -D bluealsa:DEV=B8:B3:DC:00:A2:60 /usr/share/sounds/alsa/Front_Right.wav

.asoundrc:
pcm.boombotix {
  type plug
  slave.pcm {
    type bluealsa
    device "B8:B3:DC:00:A2:60"
    profile "a2dp"
  }
}

 sudo systemctl status blue*
● bluealsa.service - BluezALSA proxy
   Loaded: loaded (/lib/systemd/system/bluealsa.service; static; vendor preset: enabled)
   Active: active (running) since Fri 2020-04-10 16:33:09 EDT; 10min ago
 Main PID: 550 (bluealsa)
    Tasks: 3 (limit: 2200)
   Memory: 924.0K
   CGroup: /system.slice/bluealsa.service
           └─550 /usr/bin/bluealsa -p a2dp-source -p a2dp-sink

Apr 10 16:33:09 pi3-8 systemd[1]: Started BluezALSA proxy.

● bluetooth.target - Bluetooth
   Loaded: loaded (/lib/systemd/system/bluetooth.target; static; vendor preset: enabled)
   Active: active since Fri 2020-04-10 16:31:59 EDT; 12min ago
     Docs: man:systemd.special(7)

Apr 10 16:31:59 pi3-8 systemd[1]: Reached target Bluetooth.

● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-04-10 16:33:09 EDT; 10min ago
     Docs: man:bluetoothd(8)
 Main PID: 548 (bluetoothd)
   Status: "Running"
    Tasks: 1 (limit: 2200)
   Memory: 1.0M
   CGroup: /system.slice/bluetooth.service
           └─548 /usr/lib/bluetooth/bluetoothd --noplugin=sap

Apr 10 16:33:09 pi3-8 systemd[1]: Started Bluetooth service.
Apr 10 16:33:09 pi3-8 bluetoothd[548]: Starting SDP server
Apr 10 16:33:09 pi3-8 bluetoothd[548]: Excluding (cli) sap
Apr 10 16:33:09 pi3-8 bluetoothd[548]: Bluetooth management interface 1.14 initialized
Apr 10 16:33:09 pi3-8 bluetoothd[548]: Endpoint registered: sender=:1.14 path=/org/bluez/hci0/A2DP/SBC/Source/1
Apr 10 16:33:09 pi3-8 bluetoothd[548]: Endpoint registered: sender=:1.14 path=/org/bluez/hci0/A2DP/SBC/Source/2
Apr 10 16:33:09 pi3-8 bluetoothd[548]: Endpoint registered: sender=:1.14 path=/org/bluez/hci0/A2DP/SBC/Sink/1
Apr 10 16:33:09 pi3-8 bluetoothd[548]: Endpoint registered: sender=:1.14 path=/org/bluez/hci0/A2DP/SBC/Sink/2
Apr 10 16:36:21 pi3-8 bluetoothd[548]: Endpoint registered: sender=:1.14 path=/org/bluez/hci0/A2DP/SBC/Source/3
Apr 10 16:41:18 pi3-8 bluetoothd[548]: /org/bluez/hci0/dev_B8_B3_DC_00_A2_60/fd5: fd(22) ready

**Comment by borine** [comment]
This is unlikely to be a bluealsa issue. Some devices always miss the very beginning of A2DP streams, others do not. I have a Libratone speaker which always misses the first 300ms, and a Sony device which never misses any of the stream. A full 1s missing does seem extreme, but still I think it is not caused by bluealsa.
