### ISSUE TITLE
wanna know why bluetooth connection is not stable when data starts to send

### ISSUE THREAD

**Issue by powerpun** [Arkq/bluez-alsa#332]
found an interesting issue

when using navigation, most of the time bluetooth will not send data out from the phone to device but when it suddenly starts to send data, data always will drop in the first several seconds

and ANDROID phone will always break during data sending (breaks in the middle) while APPLE device will have a lot stabler data transfer than ANDROID phones.

I'm wondering if this is the buffer issue caused, anybody could tell me how to fine tune this ?

**Comment by borine** [comment]
After a year without response, I think this question is unlikely to be answered here.
