### ISSUE TITLE
can run bluealsa as user bluealsa but it doesn', works as root.

### ISSUE THREAD

**Issue by hboetes** [Arkq/bluez-alsa#338]
I tried everything but I can't connect my jabra headset if bluealsa is running as user bluealsa.

```
[bluetooth]# connect 1C:48:F9:FB:FA:57
Attempting to connect to 1C:48:F9:FB:FA:57
Failed to connect: org.bluez.Error.Failed
```

Just an idea: Since group bluealsa by default has no access to /dev/snd perhaps it would be an idea to replace `;Group=bluealsa` with `;Group=audio` in the suggested systemctl file.

But even with that change which really should also user bluealsa access to the /dev/snd devices I still can't connect. And it works fine if bluealsa is running as root. What am I missing here?

**Comment by borine** [comment]
The bluealsa daemon does not connect to any local sound devices, so there is no reason to add its user to the "audio" group.

> What am I missing here?

https://github.com/Arkq/bluez-alsa/wiki/Systemd-integration#notes - see  note 2 about using non-root account

**Comment by hboetes** [comment]
Ah! I misread, the file contains more differences than just the username. Thanks for the heads up.
