### ISSUE TITLE
Couldn't acquire D-Bus name: org.bluealsa.

### ISSUE THREAD

**Issue by lfusari** [Arkq/bluez-alsa#346]
when i send a command pi@raspberrypi:~ $ bluealsa
the answer is bluealsa: Couldn't acquire D-Bus name: org.bluealsa.
I have read in the prevous post that the problem may be related to  D-Bus policy does not allow acquirire org.bluealsa but i have not unserstand how i can allow it. My device is Raspberry PI4B.
Thanks
Luca

**Comment by Arkq** [comment]
In the `/etc/dbus-1/system.d/`, there should be installed file https://github.com/Arkq/bluez-alsa/blob/master/src/bluealsa.conf in which you should set permission for bluealsa daemon access. By default it is root and audio group.
