### ISSUE TITLE
missing release tarballs

### ISSUE THREAD

**Issue by gearhead** [Arkq/bluez-alsa#350]
Maybe I am just crazy, but I've been building the release tarball for this and was looking to see if there was an update and cannot find any tar balls. 
Used to go here:
https://github.com/Arkq/bluez-alsa/archive/v${pkgver}.tar.gz
the last version I built was 2.1.0. Have you moved to git updates only or are there still releases? If it is right in front of me and I cannot see it, please let me know where to get it.

**Comment by Arkq** [comment]
I did not change anything regarding archives on github. I'm not sure if it is even possible to modify such thing :D ZIP files and tarballs are listed here: https://github.com/Arkq/bluez-alsa/releases e.g. https://github.com/Arkq/bluez-alsa/archive/v2.1.0.tar.gz

**Comment by gearhead** [comment]
My bad. I do not what is going on. Maybe it is a github update thing.  There used to be a 'Releases' tab and it is gone. You have to type it by hand, as you showed, I cannot figure out how to navigate there from the main github repository page. 

Try going to Nginx and find the releases. If you go to the code then switch between the tags to releases, you get the code view, but I have not figured out how to navigate to the tarballs other than typing it in by hand.
Sorry!

**Comment by Arkq** [comment]
![image](https://user-images.githubusercontent.com/6979798/86540085-8aef4d80-bf02-11ea-8774-1d0968190007.png)

**Comment by gearhead** [comment]
Like I said, I am a doofus. It is right in front of me, just in a different location. Thanks!
