### ISSUE TITLE
Is it possible to arecord via a2dp-sink and pipe to a2dp-source for aplay?

### ISSUE THREAD

**Issue by robertd99** [Arkq/bluez-alsa#353]
My current setup looks like this : 
<pre>
                                                  ---->3.5mm Audio-Output
                                               /
Smartphone(Bluetooth) ---> A2DP-Dongle ---> Pi2 
                                               \
                                                 ----->HDMI Audi-Output

</pre>
and 
<pre>
                                                 ---->Bluetothdongle 1 ---> Speaker 1
                                               /
                                             Pi2 
                                               \
                                                 ----->Bluetoothdongle 2 ---> Speaker 2
</pre>

My goal was to have a setup that looks like this : 
<pre>
                                                   -->Bluetooth Dongle 1-----> Audio Output 1(Speaker 1) 
                                                 /
Smartphone(Bluetooth)--> Bluetooth Dongle 0--->RPi
                                                 \ 
                                                   -->Bluetooth Dongle 2-----> Audio Output 2(Speaker 2)
</pre>

Can i have a A2DP-Sink AND Source at the same time ?

**Comment by Arkq** [comment]
Yes, you can simply enable sink and source A2DP profile and connect phone to one dongle, then setup "forwarding" with `bluealsa-aplay` and ALSA `multi` plugin. More complicated setup would involve two instances of bluealsa service - one for sink A2DP and other for source A2DP (when using only one bluealsa service, all 3 dongles will report sink and source capabilities, you will have to recognize them by MAC address or customized names set by BlueZ).

See this links:
- https://github.com/Arkq/bluez-alsa/issues/379#issuecomment-707309026
- https://github.com/Arkq/bluez-alsa/blob/master/doc/bluealsa.8.rst#example
- https://github.com/Arkq/bluez-alsa/blob/master/doc/bluealsa-aplay.1.rst

**Comment by borine** [comment]
This question was answered, and there has been no follow-up questions for 9 months since then, so closing. Please re-open if you are still working on this and have more questions,
