### ISSUE TITLE
delete defaults.bluealsa.delay ?

### ISSUE THREAD

**Issue by borine** [Arkq/bluez-alsa#401]
Since commit bbcfae4373d29d86abda495d1a10f37a190ec117 I get perfect lip sync with VLC when setting the DELAY parameter to 0. Accepting the default of 20000 for `pcm.bluealsa` causes very poor sync. (I also see the same result with chromium-browser using some multi-client code I have been working on).

Should the line
```
defaults.bluealsa.delay 20000
```
now be removed from 20-bluealsa.conf ?

**Comment by Arkq** [comment]
Yes, I think it can be removed (or set default as zero).
