### ISSUE TITLE
Asking Pin before connect to bluetooth

### ISSUE THREAD

**Issue by bawx25** [Arkq/bluez-alsa#423]
For the Security i want to have an PIN before i connect to bluetooth.

i already looked at forums and found following solving.

My bt-agent.service looks like this. But at [Service] ExecStart I added -p /root/bluetooth.cfg. 

Also in the bluetooth.config i just wrote * 1234 for the passwort.

```
cat <<'EOF' > /etc/systemd/system/bt-agent.service
[Unit]
Description=Bluetooth Agent
Requires=bluetooth.service
After=bluetooth.service
[Service]
ExecStart=/usr/bin/bt-agent --capability=NoInputNoOutput -p /root/bluetooth.cfg
RestartSec=5
Restart=always
KillSignal=SIGUSR1
[Install]
WantedBy=multi-user.target
```
But after i restart my raspi i can´t connect to bluetooth the option to write an passwort into it didnt appear.  When i try to connect it tells me, that im not allowed to connect because of an wrong pin. 

Thanks for the help

**Comment by borine** [comment]
This is not a bluealsa issue. Looks like you are asking for help about bt-agent. As no-one has answered in 3 months I recommend you seek advice from the bluez-tools project https://github.com/khvzak/bluez-tools
