### ISSUE TITLE
How to install openaptx and aac

### ISSUE THREAD

**Issue by bawx25** [Arkq/bluez-alsa#433]
I tried to install an my rarpberry pi lite os with following instruction: https://github.com/Arkq/bluez-alsa/wiki/Installation-from-source when i type
``
 ../configure --enable-aac --enable-aptx --enable-ofono --enable-msbc i get massege error that i need fdk-aac 
``
i tried to install it and get an error 

``
No package 'fdk-aac' found
``

i already tried to install it with
``
sudo apt install libfdk-aac-dev or
sudo apt install fdkaac
``
at the end i get this error
``
E: Unable to locate package libfdk-aac-dev
``

i also tried to install just openaptx this also doesn´t work and i couldn´t find an instruction which helps.

**Comment by borine** [comment]
I've now updated the wiki. For whatever reason, the RaspiOS repository has only the source package for fdk-aac, no built .deb files for either dev or runtime.
