### ISSUE TITLE
Unable to get audio output in raspberrypi

### ISSUE THREAD

**Issue by kathiravan-17** [Arkq/bluez-alsa#502]
1.disabled pluseaudio server in raspberrypi.
2.run blusealsa service as root.
3.connect BT device using bluzz and bluealsa-aplay -l able to detect the buletooth audio device .
4.while running aplay -D bluealsa:DEV=XX:XX:XX:XX:XX:XX,PROFILE=a2dp Bourree_in_E_minor.wav unable to get audio in BT speaker.
5. then changed .asoundrc in home dir ,but still unable to get audio output in bt speaker .

can anyone help to resolve the problem.

**Comment by borine** [comment]
This request for help appears to be abandoned. Closing.
