### ISSUE TITLE
configure error: checking for BLUEZ... no

### ISSUE THREAD

**Issue by hagi123456** [Arkq/bluez-alsa#53]
When installing ```bluez-alsa```, we came across the following error even though ```bluez``` was installed at version 5.43 (debian stretch):
```
checking for BLUEZ... no
configure: error: Package requirements (bluez >= 5.0) were not met:

No package 'bluez' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables BLUEZ_CFLAGS
and BLUEZ_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
After quiet a long search we found out that 
```libbluetooth-dev``` was the package that was missing. Mentioning this in the dependencies list would be great

**Comment by MiguelPerezI** [comment]
Omg thank you!!

**Comment by MiguelPerezI** [comment]
For Checking for 'bluez'                     : not found 
I never wouldǘe guessed that libbluetooth-dev would have fixed the problem.

**Comment by MiguelPerezI** [comment]
![Uploading Screenshot from 2021-03-21 17-24-14.png…]()
