### ISSUE TITLE
Latest version does always try to build msbc

### ISSUE THREAD

**Issue by hifiberry** [Arkq/bluez-alsa#541]
Since commit 36f24510bb0103e948e3b8b5b6981225f5787d88 msbc seems to be always enabled. This breaks the build if the Spandex DSP library isn't available:

codec-msbc.h:25:10: fatal error: spandsp.h: No such file or directory
   25 | #include <spandsp.h>
      |          ^~~~~~~~~~~
compilation terminated.

Latest working commit is 6509c47c27219a08a64373239469e6f7a5549303

**Comment by Arkq** [comment]
Yes, there is no `#ifdef` when codec-msbc.h is included in sco.c. I will fix that, thanks for the report.
