### ISSUE TITLE
libortp

### ISSUE THREAD

**Issue by thomas-green** [Arkq/bluez-alsa#55]
What is meant by a dependency on libortp for _compilation only_?  I would like to use your package, and am using yocto-poky for the build system.  But I don't want to bring in the entire linphone project to build this one piece. How to work around the libortp dependency?  It also seems like libortp has a dependency for bctoolbox that is not by default met as well.  As the dependency tree is growing, it seems more important to find a way to work around the libortp dependency.

**Comment by Arkq** [comment]
Hi,

Firs of all sorry for such a late response. There is a holiday time, so I do not spend much time by the computer.

After some thinking, I've removed the oRTP dependency completely. It was there merely for the RTP header definition after all :)
