### ISSUE TITLE
availability as kernel device?

### ISSUE THREAD

**Issue by smanolache** [Arkq/bluez-alsa#561]
Hello,

First thanks for this software, it is really useful for me.

Do you intend to rewrite it such that it registers a kernel device when the bluetooth audio device is paired, i.e. that the bluetooth audio device appears like a normal soundcard/device in /dev?

I couldn't make zoom work with bluetooth headsets if I insist on not using pulseaudio. It seems that zoom "sees" only the audio devices exposed by the kernel.

Thanks.

**Comment by Arkq** [comment]
No, real kernel device is beyond the scope of this project. However, you can try to use ALSA loopback device. For example see this issue: https://github.com/Arkq/bluez-alsa/issues/419 maybe it will give you a hint. Personally, I've been never setting up ALSA loopback with bluez-alsa, so I've got no real experience with that.

**Comment by smanolache** [comment]
Thank you.
