### ISSUE TITLE
alsamixer crash with codecs enum

### ISSUE THREAD

**Issue by borine** [Arkq/bluez-alsa#590]
When removing all pcms, the ctl plugin may try to fetch codecs for a pcm that is already been removed from the server and end up with no codec elem for that pcm. However, it has not yet raised an alsa elem remove event for the application, so no remove event is ever raised for that elem. As a result, alsamixer retains an invalid elem handle which will trigger an abort if later de-referenced. This simple patch fixes it:
```diff
diff --git a/src/asound/bluealsa-ctl.c b/src/asound/bluealsa-ctl.c
index f59c5cb..e0161ed 100644
--- a/src/asound/bluealsa-ctl.c
+++ b/src/asound/bluealsa-ctl.c
@@ -269,8 +269,7 @@ static int bluealsa_dev_fetch_battery(struct bluealsa_ctl *ctl, struct bt_dev *d
 static int bluealsa_pcm_fetch_codecs(struct bluealsa_ctl *ctl, struct ba_pcm *pcm,
 		struct ba_pcm_codecs *codecs) {
 
-	if (!bluealsa_dbus_pcm_get_codecs(&ctl->dbus_ctx, pcm->pcm_path, codecs, NULL))
-		return -1;
+	bluealsa_dbus_pcm_get_codecs(&ctl->dbus_ctx, pcm->pcm_path, codecs, NULL);
 
 	/* If the list of codecs could not be fetched, return currently
 	 * selected codec as the only one. This will at least allow the
```

**Comment by Arkq** [comment]
I'll look at that in a week or so. Right now I'm on vacations🌴.
