### ISSUE TITLE
Wrong Install Instructions?

### ISSUE THREAD

**Issue by KLudwig-V** [Arkq/bluez-alsa#595]
In the Wiki, on Installation from source instructions, it is stated:

Debian/Raspberry Pi OS/Ubuntu
sudo apt-get install git automake build-essential libtool pkg-config python-docutils

But to my understanding python-docutils has been replaced by software-properties-common. In any case, when trying to execute that line on the latest Raspberry PI OS I get

pi@RPi-01:~ $ sudo apt-get install git automake build-essential libtool pkg-config python-docutils
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python-docutils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-docutils' has no installation candidate

**Comment by borine** [comment]
Thanks for the heads-up. On Debian and Fedora the package should be called `python3-docutils` - I've updated the wiki page now.
