### ISSUE TITLE
Error compiling with LC3plus

### ISSUE THREAD

**Issue by Hunter-Phipps** [arkq/bluez-alsa#599]
In file included from ../../src/a2dp-sbc.c:31:
../../src/utils.h:54:30: error: unknown type name ‘LC3PLUS_Error’
   54 | const char *lc3plus_strerror(LC3PLUS_Error err);
        |                                              ^~~~~~~~~~~~~
make[3]: *** [Makefile:736: a2dp-sbc.o] Error 1

**Comment by Arkq** [comment]
Do you have LC3plus (not LC3) library installed? The lc3.h from lc3plus defines `typdef enum { ... } LC3PLUS_Error;`.

**Comment by Hunter-Phipps** [comment]
I compiled libLC3plus.so using the makefile changes in https://github.com/Arkq/bluez-alsa/issues/479 and copied it into the /usr/lib/ folder.

**Comment by Arkq** [comment]
Please, check from where the `lc3.h` is included with command like this: `echo '#include <lc3.h>' | gcc -H -x c -` Then, check whether the included `lc3.h` file has LC3PLUS_Error definition.

**Comment by Hunter-Phipps** [comment]
I copied lc3.h and lc3.c from the ETSI floating point source code to /usr/include/ and it looks like it compiled / installed without any issues but I still don't see LC3 in the pipewire compile.

**Comment by Arkq** [comment]
> but I still don't see LC3 in the pipewire compile

Hmm... you might be right, because this repo is not for pipewire project :D

But if you meant that in pipewire LC3plus (not LC3) is not activated when connecting with bluealsa, make sure that LC3plus is enabled in bluealsa via command line options, i.e.: `bluealsa -p a2dp-source -c lc3plus`.

**Comment by arkq** [comment]
Since there are no more replies, I understand that the issues is solved. Otherwise, please reopen it and provide more details about your setup.
