### ISSUE TITLE
Handsfree Audio Gateway issue

### ISSUE THREAD

**Issue by Pro-pra** [Arkq/bluez-alsa#62]
Hi Arkq,

Some mobile phone have Handsfree Audio Gateway service, UUID - 111E or 111F.
How to use this service more correctly? can bluez-alsa help for use this service?

**Comment by Arkq** [comment]
It is possible to use HFP AG feature. Just connect your phone with a PC where bluealsa is running. However, this feature is still under development.

And to be perfectly clear. Bluealsa supports (will support) only audio-related feature of the HFP.

**Comment by Pro-pra** [comment]
Yes, this is a more complex algorithm. Handsfree means using the answer and end-of-call signals that you can not transfer from the PC
