### ISSUE TITLE
airpods3 failed to connect back

### ISSUE THREAD

**Issue by luoyuyi111** [arkq/bluez-alsa#626]
hi,
I found the airpods3 after successfully connecting, turn off it. Then turn on the airpods3 . At this time, the connection will automatically return, and the return will fail.    

Bluealsa will prompt "bluealsa: Invalid configuration: Invalid object type“.  From hcilog see airpods3  simultaneously set MPEG-2 AAC LC, MPEG-4 AAC LC caused.

**Comment by borine** [comment]
> bluealsa: Invalid configuration: Invalid object type

It seems you are using an old release of BlueALSA. That error message was removed in release 3.0.0 (September 2020), so your release must be from before that. I guess you obtained it from your OS distribution repository. Could that be the RaspberryPi repo by any chance?

**Comment by arkq** [comment]
> It seems you are using an old release of BlueALSA.

Yes, this issue was fixed some time ago (I do not remember which commit fixes it, though). Please, use the latest release (currently 4.0.0).

**Comment by luoyuyi111** [comment]
> > bluealsa: Invalid configuration: Invalid object type
> 
> It seems you are using an old release of BlueALSA. That error message was removed in release 3.0.0 (September 2020), so your release must be from before that. I guess you obtained it from your OS distribution repository. Could that be the RaspberryPi repo by any chance?

I'm currently using V3.1.0, which doesn't seem to be fixed. I'll try it on the latest version later. thanks
