### ISSUE TITLE
 bluez-alsa in mobile

### ISSUE THREAD

**Issue by yangte** [Arkq/bluez-alsa#66]
Hey!
we use bluez-alsa in Android 7.0 mobile ,it works well,but we find that music has problem with caton when we use mgmt start discovery.can you give me some suggestions?
Thanks again and let me know if you need some help!

**Comment by Arkq** [comment]
Hi,

I'm sorry, but I'm not able to help you I'm afraid. I was not aware, that it is possible to run bluez-alsa on Android (I though, that Android does not use Bluez as a Bluetooth stack) :D.

All I can say, is that the discovery mode (if you mean Bluetooth devices discovery), does not play very well with data transfer (reported in other issues).

**Comment by yangte** [comment]
yes,you are right.most android mobile use bluedroid as bluetooth,but we do a system os ,so we choose blueZ as bluetooh stack.now we use bluealsa solve the blueZ compatibility with autdioflinger。we find open transport need to set broadcom QOS high,and stop transport set broadcom QOS low.this operation may solve when  discovery device audio can not play very well.

**Comment by yangte** [comment]
but now we find use audioflinger to play music will have Last frame sound when pause and resume. can you give me some suggestions?Thanks again and let me know if you need some help!

**Comment by Arkq** [comment]
Closing stale issue.
