### ISSUE TITLE
build/install: LC3Plus libraries??

### ISSUE THREAD

**Issue by iconoclasthero** [arkq/bluez-alsa#684]
> Please read the [troubleshooting guide](../blob/master/TROUBLESHOOTING.md)
> before raising a new issue.

### Problem

can't figure out how to get LC3Plus support to work...

### Reproduction steps
$ sudo cp $HOME/bin/gits/LC3plus/src/floating_point/lc3plus.h /usr/local/include
../configure --enable-lc3plus ...
⋮
checking for lc3plus.h... yes
checking for lc3plus_version, lc3plus_enc_set_frame_dms in -lLC3plus... no
configure: error: LC3plus library not found

##

From the looks of it, the LC3plus library support is support for your libraries.  How do I make these work together?  I already installed the google/liblc3.

**Comment by arkq** [comment]
> How do I make these work together? I already installed the google/liblc3.

For LC3plus support you need to install Fraunhofer liblc3plus library (not google's one, bluez-alsa does not support LC3plus with liblc3, not yet). Please follow the guideline in https://github.com/arkq/bluez-alsa/wiki/Installation-from-source#additional-dependencies (or go directly to https://github.com/arkq/bluez-alsa/issues/479#issuecomment-1618857445)

**Comment by iconoclasthero** [comment]
Thanks
