### ISSUE TITLE
Test all deps with pkgconfig

### ISSUE THREAD

**Issue by sergey-suloev** [arkq/bluez-alsa#687]
Could you use pkgconfig while testing deps, please ? 
For example, mp3lame is tested with gcc and this is a big headache while cross-compiling.

**Comment by borine** [comment]
Does libmp3lame have a pkgconfig file? My Ubuntu and RaspberrypiOS installations do not have a libmp3lame.pc, nor a lame.pc.

**Comment by sergey-suloev** [comment]
Of course it does !  I am using stable debian , package libmp3lame-dev

**Comment by borine** [comment]
- Ah, OK I've just checked. There is a lame.pc in debian bookworm (libmp3lame-dev 3.100-6) but not in debian buster (libmp3lame-dev 3.100-3). So it is a relatively recent addition. I don't see it in the upstream mp3lame sources though.

**Comment by arkq** [comment]
Unfortunately, the only reliable way of checking for the libmp3lame is testing for the library presence... Upstream has never provided support for pkg-config. There are some distributions which patch their devel package with pkg-config (like Gentoo or the latest Debian), but most distributions do not...

**Comment by sergey-suloev** [comment]
I think the best solution would be using both methods

**Comment by arkq** [comment]
Put apparently things are moving in the right direction:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829327
https://sourceforge.net/p/lame/feature-requests/42/

**Comment by sergey-suloev** [comment]
> Put apparently things are moving in the right direction: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829327 https://sourceforge.net/p/lame/feature-requests/42/

That's really ridiculous how long the discussion had been going while the problem itself needs 3 minutes of work

**Comment by arkq** [comment]
> That's really ridiculous how long the discussion has been lasting in community while the problem itself needs 3 minutes of work

That's the case where there are no incentives involved. In open source community no one wants extra things which needs to be maintained (for free) later :D

> I think the best solution would be using both methods , pkgconfig first and lib testing as a fallback

Since the `lame.pc` will land in the next release of mp3lame, I think that we can add support for that.

**Comment by sergey-suloev** [comment]
thank you

**Comment by arkq** [comment]
I've added pkg-config support for LAME. The only library which still does not have pkg-config support is LC3plus (it's not available in the upstream). In the future, LC3plus will be supported via Google's LC3 library too (which does have pkg-config support), so stay tuned.
