### ISSUE TITLE
`alsaaudio.ALSAAudioError: Invalid argument` with BlueALSA due to no matching configuration

### ISSUE THREAD

**Issue by follower** [Arkq/bluez-alsa#78]
This is primarily a "pointer" to the following issue in case someone else encounters it: https://github.com/larsimmisch/pyalsaaudio/issues/45

While it might be possible to workaround the issue within BlueALSA code or configuration it seems the underlying issue is with `pyalsaaudio`.

I encountered the issue with Raspbian on a Raspberry Pi 3.

**Comment by borine** [comment]
The referenced issue was closed in July 2020
