### ISSUE TITLE
Blualsa support with OpenWRT

### ISSUE THREAD

**Issue by PraneetKaur** [Arkq/bluez-alsa#80]
Hi,
I would like to know if bluealsa is supported on OpenWRT platform. I am trying to get audio streaming with bluez5.37 using A2DP. I want to enable both A2DP source and A2DP sink for audio streaming purpose.

Thanks

**Comment by diizzyy** [comment]
https://github.com/openwrt/packages/pull/6010 might be of interest

**Comment by Rixerx** [comment]
@Arkq Arek it is any chance of taking maintenance by You of bluez-alsa package in OpenWrt repo?

**Comment by raphikWasHere** [comment]
[This](https://foro.seguridadwireless.net/openwrt/der-router-als-bluetooth-lautsprecher/ ) might be of service.

**Comment by Arkq** [comment]
Since there is an example of how to use bluez-alsa with OpenWRT, I'm closing this issue, because maintaining distribution packaging is of of the bluez-alsa issues scope.
