### ISSUE TITLE
Small consultation need please

### ISSUE THREAD

**Issue by Pro-pra** [Arkq/bluez-alsa#87]
Dear Arkq, maybe you know how to create a serial connection (make /dev/rfcomm0 port) without using rfcomm, using only dbus command. (i use dbus-send from my scripts).

Bluez5 code examples are written on a python, I can not understand them.

**Comment by Arkq** [comment]
It seems, there is a `rfcomm` utility, which should be used for managing RFCOMM. Unfortunately, I've got no such a program installed on my box... Maybe, BlueZ needs to be configured somehow specially during compilation...

**Comment by infirit** [comment]
We have some c code to create and release rfcomm devices. See https://github.com/blueman-project/blueman/blob/05eea0db0cacf888629d7d23ca62c73d663e98f2/module/libblueman.c#L412

**Comment by Arkq** [comment]
Thx @infirit for this code. And what are the benefits of creating `/dev/rfcomm0`? Maybe bluealsa should create it after HFP/HSP connection... what do you think?

**Comment by Pro-pra** [comment]
Yes, I know about the utility rfcomm, but now it is deprecated. Now i use rfcomm in my bash script.

I want to learn how to make the interface through Dbus, in the future it will be necessary to create interfaces for Ethernet interface. Make Com device is example for other work with bluez5 via Dbus.

**Comment by Pro-pra** [comment]
i send message to linux-bluetooth mailinglist
