### ISSUE TITLE
No sound in chromium

### ISSUE THREAD

**Issue by phaoost** [Arkq/bluez-alsa#88]
Hello,

I am not getting any sound in chromium when using bluealsa.
I get the following messages:

`ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default`
`ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM plug:default`

**Comment by Pro-pra** [comment]
asoundrc post here please

**Comment by phaoost** [comment]
~$ cat .asoundrc
pcm.headset {
        type plug
        slave.pcm {
                type bluealsa
                device "B8:69:C2:CF:01:AB"
                profile "a2dp"
#               delay -20000
        }
        hint {
                show on
                description "BT Headset"
        }
}

**Comment by Pro-pra** [comment]
My example.

   pcm.!default {
   type plug
   slave.pcm {
           type bluealsa
           device "XX:XX:XX:XX:XX:XX"
           profile "a2dp"
  }
}
ctl.!default {
  type bluetooth
  interface "XX:XX:XX:XX:XX:XX"
}

**Comment by phaoost** [comment]
I have tried your example, just changed address and gotten the following output from chromium:
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL hw:0
[51:68:0227/082139.340815:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Output device error, falling back to null sink"}
I have checked VLC and it worked with these settings

**Comment by Pro-pra** [comment]
interface set to you hci0 device adress.

**Comment by phaoost** [comment]
Ok I have tried as instructed and now only gotten:
[70:102:0228/102504.498971:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Output device error, falling back to null sink"}

Still no sound in chromium

**Comment by Pro-pra** [comment]
you use pulseaudio? if not use pulseaudio, install apulse package

**Comment by Arkq** [comment]
@phaoost Assuming that your `.asoundrc` looks like in [your previous comment](https://github.com/Arkq/bluez-alsa/issues/88#issuecomment-368438452), try something like this:

`chromium --alsa-output-device=headset`

If it does not work either, compile `bluez-alsa` with debug enabled and post here the output from the chromium (preferably using the command above).

**Comment by phaoost** [comment]
Ok I have finally managed to make it work.
I did not use apulse and there is no pulseaudio on my pc

I've run:
~$ LIBASOUND_THREAD_SAFE=0 ALSA_CONFIG_PATH=~/.asoundrc.bt chromium

The only output I have gotten from ALSA is:
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL hw:0

~/.asoundrc.bt contents:

```
pcm.!default {
        type plug
        slave.pcm {
                type bluealsa
                device "B8:69:C2:CF:01:AB"
                profile "a2dp"
        }
}
ctl.!default {
        type bluetooth
        interface "44:85:00:9E:A3:1C"
}
```
