### ISSUE TITLE
<printf.h> only available in glibc

### ISSUE THREAD

**Issue by joerg-krause** [Arkq/bluez-alsa#90]
<printf.h> is only available in glibc. Building from master with a musl toolchain fails, because `printf.h` is not found. Is `printf.h` only needed in debug build (DEBUG is defined)? At least, I can compile when guarding the include statement with `#if DEBUG ... #endif`.

EDIT: <printf.h> **not** <fprintf.h>

**Comment by Arkq** [comment]
Sorry, but I don't understand your case...
There is no `#include <fprintf.h>` in the bluez-alsa codebase. Moreover, `fprintf()` is conforming to: POSIX.1-2001, POSIX.1-2008, C89 and C99.

**Comment by joerg-krause** [comment]
Sorry, my bad! I meant <printf.h> **not** <fprintf.h>.

**Comment by joerg-krause** [comment]
Thanks for the quick fix!

**Comment by Arkq** [comment]
No problem ;)
